#include <stdint.h>
#include <stdio.h>

#define F7_STANDARD 0x00 // 0000000 (es. ADD, SRL)
#define F7_ALTERNATE 0x20 // 0100000 (es. SUB, SRA)

#define DEBUG
#define IMEM_SIZE 1024 
#define DM_OFFSET 0x10010000
#define IM_OFFSET 0x400000
#define ADDR_BITS 10
#define DMEM_MASK (0xFFFFFFFF >> (32 - (ADDR_BITS)))

#define LOGFILE_NAME "log_gs.txt"     //name of the file generated by the program with the log of executed instructions
#define IMEM_FILE    "main.bin"       //standard file name for instruction memory content

uint32_t imem[IMEM_SIZE];             // Instruction memory organized in 32-bit words
uint8_t dmem[1024 * 4];  

typedef struct {
    uint32_t OP;           // ISA instruction to be executed.
    uint32_t opcode;
    uint32_t dr;           // destination register
    uint32_t immediate;
    uint32_t funct3;
    uint32_t rs1;
    uint32_t rs2;
    uint32_t funct7;
} InstructionInfo;

InstructionInfo current_instruction;

typedef enum 
{
    OPCODE_R        = 0x33,
    OPCODE_I        = 0x13,
    OPCODE_LOAD     = 0x03,
    OPCODE_S        = 0x23,
    OPCODE_B        = 0x63,
    OPCODE_LUI      = 0x37,
    OPCODE_AUIPC    = 0x17,
    OPCODE_JAL      = 0x6F,
    OPCODE_JALR     = 0x67,
    OPCODE_SYSTEM   = 0x73,
    OPCODE_FENCE    = 0x0F
} RISCV_Opcode;


typedef enum {
    F3_BEQ  = 0x0, // 000
    F3_BNE  = 0x1, // 001
    F3_BLT  = 0x4, // 100
    F3_BGE  = 0x5, // 101
    F3_BLTU = 0x6, // 110
    F3_BGEU = 0x7  // 111
} F3_Branch;

typedef enum {
    F3_ADDSUB = 0x0, // ADD o SUB
    F3_SLL    = 0x1, // Shift Left Logical
    F3_SLT    = 0x2, // Set Less Than
    F3_SLTU   = 0x3, // Set Less Than Unsigned
    F3_XOR    = 0x4, // XOR
    F3_SR     = 0x5, // SRL (Logical) o SRA (Arithmetic)
    F3_OR     = 0x6, // OR
    F3_AND    = 0x7  // AND
} F3_ALU;

typedef enum {
    F3_B  = 0x0, // Byte (LB, SB)
    F3_H  = 0x1, // Half (LH, SH)
    F3_W  = 0x2, // Word (LW, SW)
    F3_BU = 0x4, // Byte Unsigned (LBU)
    F3_HU = 0x5  // Half Unsigned (LHU)
} F3_DataSize;

const char *ISA_names[] = {
    "ADD", "SUB", "SLL", "SLT", "SLTU", "XOR", "SRL", "SRA", "OR", "AND",
    "ADDI", "SLTI", "SLTIU", "XORI", "ORI", "ANDI", "SLLI", "SRLI", "SRAI",
    "LB", "LH", "LW", "LBU", "LHU",
    "SB", "SH", "SW", "BEQ", "BNE", "BLT", "BGE", "BLTU", "BGEU",
    "LUI", "AUIPC", "JAL", "JALR",
    "ECALL", "EBREAK", "FENCE"
};

typedef enum {
    // --- Tipo R (Register-Register) ---
    ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND,

    // --- Tipo I (Immediate & Load) ---
    ADDI, SLTI, SLTIU, XORI, ORI, ANDI, SLLI, SRLI, SRAI,
    LB, LH, LW, LBU, LHU,

    // --- Tipo S (Store) ---
    SB, SH, SW,

    // --- Tipo B (Branch) ---
    BEQ, BNE, BLT, BGE, BLTU, BGEU,

    // --- Tipo U (Upper Immediate) ---
    LUI, AUIPC,

    // --- Tipo J (Jump) ---
    JAL, JALR,

    // --- Sistema & Speciali ---
    ECALL, EBREAK, FENCE,
    
    ISA_COUNT 
} ISA;

int32_t registerFile[32]; 


uint32_t PC;
uint32_t next_PC;
uint32_t address_dm;
uint32_t fetched_instr = 0x0;

int fetch       ( uint32_t * current_instr);
void decode     ( uint32_t instr );
void execute    ( InstructionInfo *instr );
void print_log  ( FILE *fp );
int  Init_Memories(char * imem_file, char *dmem_file);
FILE*  open_LogFile();
uint8_t is_reg_write (ISA op);
uint8_t is_mem_access(ISA op);
void print_instr_memory();
void print_data_memory(int n);

uint32_t current_instr = 0x0; 

uint8_t  stop = 0;
uint32_t cycles = 0;

int main(int argc, char *argv[])
{

    FILE *fp;
    int i = 0;
    char line[10];

    char *imem_file = IMEM_FILE;
    char *dmem_file = "data_mem.txt";


    registerFile[0] = 0; // x0 register is a constant zero in RISC-V

    //if program is launched with arguments, use them as imem and dmem files, otherwise use default ones
    if(argc > 1 )
    {
        imem_file = argv[1];
        if (argc > 2 )
        {
            dmem_file = argv[2];
        }
    }

    if ( Init_Memories(imem_file, dmem_file) != 0 ) return -1;

    if ( ( fp = open_LogFile()) == NULL ) return -1;


    PC = IM_OFFSET;               //starting address of the COMPILED PROGRAM
    next_PC = PC;

#ifdef DEBUG
    //print_instr_memory();
     print_data_memory(10);
#endif

      while((!stop && cycles < 10000)  && registerFile[3] != 0x1 )
    {

        if(fetch( &fetched_instr ) != 0) return -1;

        decode( fetched_instr );

        execute( &current_instruction );

        cycles++;
        print_log( fp );

        PC = next_PC; // Update PC to the next instruction address

    }

    // Print final register state
#ifdef DEBUG
    fprintf(fp, "\n\n");
    for(int i = 0; i < 32; i++)
        fprintf(fp, "* reg_%-4d: 0x%08X *\n", i, registerFile[i]);
#endif
        
    fclose( fp );
}



void execute(InstructionInfo *instr) {

    // Supponiamo che dr, sr1, sr2 siano alias per instr->rd, instr->rs1, instr->rs2
    uint32_t dr = instr->dr;
    uint32_t val1 = registerFile[instr->rs1];
    uint32_t val2 = registerFile[instr->rs2];

    int32_t imm = instr->immediate;    //addressm for data memory starts at 0x10010000  

    switch(instr->OP) {
        // --- Operazioni Aritmetiche R-Type e I-Type ---
        case ADD:  registerFile[dr] = val1 + val2; next_PC= PC + 4; break;
        case ADDI: registerFile[dr] = val1 + imm;  next_PC= PC + 4; break;
        case SUB:  registerFile[dr] = val1 - val2; next_PC= PC + 4; break;
        
        case AND:  registerFile[dr] = val1 & val2; next_PC= PC + 4; break;
        case ANDI: registerFile[dr] = val1 & imm;  next_PC= PC + 4; break;
        
        case OR:   registerFile[dr] = val1 | val2; next_PC= PC + 4; break;
        case ORI:  registerFile[dr] = val1 | imm;  next_PC= PC + 4; break;
        
        case XOR:  registerFile[dr] = val1 ^ val2; next_PC= PC + 4; break;
        case XORI: registerFile[dr] = val1 ^ imm;  next_PC= PC + 4;break;

        // --- Operazioni di Shift ---
        case SLL:  registerFile[dr] = val1 << (val2 & 0x1F); next_PC= PC + 4; break; // Shift Left Logical
        case SLLI: registerFile[dr] = val1 << (imm & 0x1F);  next_PC= PC + 4; break;
        case SRL:  registerFile[dr] = val1 >> (val2 & 0x1F); next_PC= PC + 4;break; // Shift Right Logical
        case SRLI: registerFile[dr] = val1 >> (imm & 0x1F);  next_PC= PC + 4; break;
        case SRA:  registerFile[dr] = (int32_t)val1 >> (val2 & 0x1F); next_PC= PC + 4; break; // Shift Right Arithmetic
        case SRAI: registerFile[dr] = (int32_t)val1 >> (imm & 0x1F);  next_PC= PC + 4; break;

        // --- Comparazioni (Set Less Than) ---
        case SLT:   registerFile[dr] = ((int32_t)val1 < (int32_t)val2) ? 1 : 0; next_PC= PC + 4; break;
        case SLTI:  registerFile[dr] = ((int32_t)val1 < (int32_t)imm) ? 1 : 0;  next_PC= PC + 4;  break;
        case SLTU:  registerFile[dr] = (val1 < val2) ? 1 : 0; next_PC= PC + 4; break;
        case SLTIU: registerFile[dr] = (val1 < (uint32_t)imm) ? 1 : 0; next_PC= PC + 4; break;

        // --- Store Instructions (Accesso a 8-bit in dmem) ---
        case SB:
        //    address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm) ; // Limitiamo l'indirizzo a 1024 byte (1KB) di dmem 
            dmem[address_dm & DMEM_MASK ] = val2 & 0xFF;
            next_PC= PC + 4;
            break;
        case SH:
        //    address_dm = val1 + imm - DM_OFFSET; 
            address_dm = (val1 + imm) ;
            dmem[address_dm & DMEM_MASK] = val2 & 0xFF;
            dmem[(address_dm & DMEM_MASK) + 1] = (val2 >> 8) & 0xFF;    
            next_PC= PC + 4;
            break;
        case SW:
        //    address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm) ;
            printf("Immeidate : %d at cyc: %d \n", imm, cycles);
            dmem[address_dm & DMEM_MASK] = val2 & 0xFF;
            dmem[(address_dm & DMEM_MASK) + 1] = (val2 >> 8)  & 0xFF;
            dmem[(address_dm & DMEM_MASK) + 2] = (val2 >> 16) & 0xFF;
            dmem[(address_dm & DMEM_MASK) + 3] = (val2 >> 24) & 0xFF;
            next_PC= PC + 4;
            break;

        // --- Load Instructions ---
        case LB:
        //    address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm) ;
            registerFile[dr] = (int8_t)dmem[address_dm & DMEM_MASK]; // Estensione segno automatica
            next_PC= PC + 4;
            break;
        case LBU:
        //    address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm) ;
            registerFile[dr] = dmem[address_dm & DMEM_MASK]; // Zero extended
            next_PC= PC + 4;
            break;
        case LH:
        //    address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm) ;
            registerFile[dr] = (int16_t)(dmem[address_dm & DMEM_MASK] | (dmem[(address_dm & DMEM_MASK )+1] << 8));
            next_PC= PC + 4;
            break;
        case LHU:
        //    address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm) ;
            registerFile[dr] = (uint16_t)(dmem[address_dm & DMEM_MASK] | (dmem[(address_dm & DMEM_MASK )+1] << 8));
            next_PC= PC + 4;
            break;
        case LW:
            //address_dm = val1 + imm - DM_OFFSET;
            address_dm = (val1 + imm);
            registerFile[dr] = (dmem[address_dm  & DMEM_MASK]) | (dmem[( address_dm  & DMEM_MASK )+1] << 8) | 
                               (dmem[(address_dm  & DMEM_MASK )+2] << 16) | (dmem[(address_dm  & DMEM_MASK ) +3] << 24);
            next_PC= PC + 4;
            break;

        // --- Branch Instructions (Gestione PC) ---
        case BEQ:  if(val1 == val2) next_PC = PC + imm ; else next_PC = PC + 4; break;
        case BNE:  if(val1 != val2) next_PC = PC + imm ; else next_PC = PC + 4; break;
        case BLT:  if((int32_t)val1 < (int32_t)val2)  next_PC = PC + imm ;  else next_PC = PC + 4; break;
        case BGE:  if((int32_t)val1 >= (int32_t)val2) next_PC = PC + imm;   else next_PC = PC + 4; break;
        case BLTU: if(val1 < val2) next_PC =PC + imm ;  else next_PC = PC + 4; break;
        case BGEU: if(val1 >= val2) next_PC =PC + imm ; else next_PC = PC + 4; break;

        // --- Jump & Upper Imm ---
        case JAL:
            registerFile[dr] = PC + 4;
            next_PC = PC + imm;
            break;
        case JALR:
            {
                uint32_t target = (val1 + imm) & ~1; // Azzera bit meno significativo
                registerFile[dr] = PC + 4;
                next_PC = target;
            }
            break;
        case LUI:
            //registerFile[dr] = imm << 12;
            registerFile[dr] = imm;
            next_PC = PC + 4;
            break;
        case AUIPC:
//            registerFile[dr] = PC + (imm << 12);
            registerFile[dr] = PC + imm;
            next_PC = PC + 4;
            break;

        case FENCE:
            // just incremente pc for now.
            next_PC = PC + 4;
            break;

        case EBREAK:
        // usign EBREAK for ending simulation
            stop = 1;
            break;
        
        case ISA_COUNT:
            next_PC = PC + 4;
        break;
    }

    // REGISTRO X0 SEMPRE ZERO
    registerFile[0] = 0;
    
}

void decode( uint32_t istr )
{
    current_instruction.opcode = istr & 0x7F;

    switch (current_instruction.opcode)
    {
        case OPCODE_R:
            current_instruction.dr      = (istr >> 7) & 0x1F;
            current_instruction.funct3  = (istr >> 12) & 0x7;
            current_instruction.rs1     = (istr >> 15) & 0x1F;
            current_instruction.rs2     = (istr >> 20) & 0x1F;
            current_instruction.funct7  = (istr >> 25);

            switch (current_instruction.funct3)
            {
                case F3_ADDSUB:
                    current_instruction.OP = (current_instruction.funct7 == F7_STANDARD) ? ADD : SUB;
                    break;

                case F3_SLL: current_instruction.OP = SLL; break;
                case F3_SLT: current_instruction.OP = SLT; break;
                case F3_SLTU: current_instruction.OP = SLTU; break;
                case F3_XOR: current_instruction.OP = XOR; break;

                case F3_SR:
                    current_instruction.OP = (current_instruction.funct7 == F7_STANDARD) ? SRL : SRA;
                    break;

                case F3_OR: current_instruction.OP = OR; break;
                case F3_AND: current_instruction.OP = AND; break;
            }
            break;

        case OPCODE_I:
            current_instruction.dr  = (istr >> 7) & 0x1F;
            current_instruction.funct3 = (istr >> 12) & 0x7;
            current_instruction.rs1 = (istr >> 15) & 0x1F;
            current_instruction.immediate = (int32_t)istr >> 20;

            switch (current_instruction.funct3)
            {
                case F3_ADDSUB: current_instruction.OP = ADDI; break;
                case F3_SLL: current_instruction.OP = SLLI; break;
                case F3_SLT: current_instruction.OP = SLTI; break;
                case F3_SLTU: current_instruction.OP = SLTIU; break;
                case F3_XOR: current_instruction.OP = XORI; break;

                case F3_SR:
                    current_instruction.funct7 = (istr >> 25);
                    current_instruction.OP = (current_instruction.funct7 == F7_STANDARD) ? SRLI : SRAI;
                    break;

                case F3_OR: current_instruction.OP = ORI; break;
                case F3_AND: current_instruction.OP = ANDI; break;
            }
            break;

        case OPCODE_LOAD:
            current_instruction.dr  = (istr >> 7) & 0x1F;
            current_instruction.funct3 = (istr >> 12) & 0x7;
            current_instruction.rs1 = (istr >> 15) & 0x1F;
            current_instruction.immediate = (int32_t)istr >> 20;

            switch (current_instruction.funct3)
            {
                case F3_B:  current_instruction.OP = LB; break;
                case F3_H:  current_instruction.OP = LH; break;
                case F3_W:  current_instruction.OP = LW; break;
                case F3_BU: current_instruction.OP = LBU; break;
                case F3_HU: current_instruction.OP = LHU; break;
            }
            break;

        case OPCODE_S:
            current_instruction.immediate =
                ((int32_t)(istr & 0xFE000000) >> 20) | 
                ((istr >> 7) & 0x1F);

            current_instruction.funct3 = (istr >> 12) & 0x7;
            current_instruction.rs1 = (istr >> 15) & 0x1F;
            current_instruction.rs2 = (istr >> 20) & 0x1F;

            switch (current_instruction.funct3)
            {
                case F3_B: current_instruction.OP = SB; break;
                case F3_H: current_instruction.OP = SH; break;
                case F3_W: current_instruction.OP = SW; break;
            }
            break;

        case OPCODE_B:
            current_instruction.immediate =
                ((int32_t)(istr & 0x80000000) >> 19) | // imm[12] + sign extension
                ((istr & 0x00000080) << 4)           | // imm[11]
                ((istr & 0x7E000000) >> 20)          | // imm[10:5]
                ((istr & 0x00000F00) >> 7);            // imm[4:1]  

            current_instruction.funct3 = (istr >> 12) & 0x7;
            current_instruction.rs1 =    (istr >> 15) & 0x1F;
            current_instruction.rs2 =    (istr >> 20) & 0x1F;

            switch (current_instruction.funct3)
            {
                case F3_BEQ: current_instruction.OP = BEQ; break;
                case F3_BNE: current_instruction.OP = BNE; break;
                case F3_BLT: current_instruction.OP = BLT; break;
                case F3_BGE: current_instruction.OP = BGE; break;
                case F3_BLTU: current_instruction.OP = BLTU; break;
                case F3_BGEU: current_instruction.OP = BGEU; break;
            }
            break;

        case OPCODE_JAL:
            current_instruction.dr = (istr >> 7) & 0x1F;
            current_instruction.immediate =
                ((int32_t)(istr & 0x80000000) >> 11) | // Bit 20 (e estensione segno ai bit 31:21)
                (istr & 0x000FF000)                  | // Bit 19:12
                ((istr >> 9) & 0x00000800)           | // Bit 11
                ((istr >> 20) & 0x000007FE);

            current_instruction.OP = JAL;
            break;

        case OPCODE_JALR:
            current_instruction.dr = (istr >> 7) & 0x1F;
            current_instruction.rs1 = (istr >> 15) & 0x1F;
            current_instruction.immediate = (int32_t)istr >> 20;
            current_instruction.OP = JALR;
            break;

        case OPCODE_LUI:
            current_instruction.dr = (istr >> 7) & 0x1F;
            current_instruction.immediate = istr & 0xFFFFF000;
            current_instruction.OP = LUI;
            break;

        case OPCODE_AUIPC:
            current_instruction.dr = (istr >> 7) & 0x1F;
            current_instruction.immediate = istr & 0xFFFFF000;
            current_instruction.OP = AUIPC;
            break;
        
        case OPCODE_FENCE:
            current_instruction.OP = FENCE;          
            break;

        default:
        // No valid instruction risc-v 32i instruction
            current_instruction.OP = ISA_COUNT; // Invalid OP code
          
        break;

    }
}

int fetch(uint32_t * current_instr)
{

    uint32_t addr = (PC - IM_OFFSET) >> 2;
    if(addr < IMEM_SIZE)
    {
        *current_instr = imem[addr];
        return 0;
        
    } else {
        printf("Error: Program Counter out of bounds! iaddr: 0x%08X\n", addr);
        printf("CYC : %d; istr: %s", cycles, ISA_names[current_instruction.OP]);
        *current_instr = 0; // NOP
        return -1;
    }
}

/// @brief Intialises instruction and data memories by reading from "imem.bin" and "data_mem.txt" files respectively.
/// @return 

int Init_Memories(char * imem_file, char *dmem_file)
{
    char line[10];
    int i = 0;
    char buffer[255];
    uint32_t word;

    FILE *fp;

    fp = fopen(imem_file, "r");
    if(fp == NULL) {
        perror("Error opening imem file!#\n");
        return -1;
    }

    //jump first two lines of the imem file, used for metadata
#if 0
    for(int i=0; i < 2; i++)
        fgets(buffer, sizeof(buffer), fp);
#endif

    while ( fgets(line, sizeof( line ), fp) != NULL )
    {
        sscanf(line, "%x", &imem[i]);
        i++;
    }

    fclose(fp);

    i = 0;

    fp = fopen(dmem_file, "r");
    if(fp == NULL) {
        perror("Error opening file for writing dmem!");
        return -1;
    }
    //data memory loading
    while ( fgets(line, sizeof( line ), fp) != NULL )
    {
    //    sscanf(line, "%x", &dmem[i]);
        sscanf(line, "%x", &word );

        printf("%x \n", word);

        dmem[i]   = (uint8_t) (word & 0xFF);
        dmem[i+1] = (uint8_t)((word >> 8)  & 0xFF);
        dmem[i+2] = (uint8_t)((word >> 16) & 0xFF); 
        dmem[i+3] = (uint8_t)((word >> 24) & 0xFF);
        i += 4;
    }

    return 0; 
}

FILE* open_LogFile()
{
    FILE *fp;
    fp = fopen(LOGFILE_NAME,"w");
    if ( fp == NULL )
    {
        perror("Error opening log file!\n");
        return NULL;
    }

    // write first line of the file
    fprintf(fp, "=== RISC-V 32I Instruction Set Simulator Log ===\n\n");

                //12          14                 8           12             12             14              14
    fprintf(fp, "PC       |  INSTR   |   OP   | REG_DEST | REG_DATA | MEM_ADDR |  MEM_DATA\n");

    return fp;
}


void print_log( FILE *fp )
{

    uint32_t log_addr_dm = 0;
    uint32_t log_dmem_data = 0;
    uint32_t log_reg_data = 0;

    if(is_reg_write(current_instruction.OP)) {
        log_reg_data = registerFile[current_instruction.dr];
    }

    if(is_mem_access(current_instruction.OP)) {

        log_addr_dm = address_dm;
 //       address_dm -= (address_dm % 4); // Aligning address to word boundary for memory access

        if( current_instruction.OP == SB)
        {
            log_dmem_data = dmem[address_dm & DMEM_MASK] | (dmem[address_dm & DMEM_MASK] << 8) | 
                           (dmem[address_dm & DMEM_MASK] << 16) | (dmem[address_dm & DMEM_MASK] << 24);
        }
        else if( current_instruction.OP == SH)
        {
            log_dmem_data = (dmem[address_dm & DMEM_MASK]) | (dmem[(address_dm + 1) & DMEM_MASK] << 8) | 
                            (dmem[address_dm & DMEM_MASK] << 16) | (dmem[(address_dm + 1) & DMEM_MASK] << 24);
        }
        else
            log_dmem_data = (dmem[address_dm & DMEM_MASK]) | (dmem[(address_dm + 1)& DMEM_MASK] << 8) | 
                        (dmem[(address_dm + 2) & DMEM_MASK] << 16) | (dmem[(address_dm + 3) & DMEM_MASK] << 24);

    } 
    
 //   printf("%s \n",   ISA_names[current_instruction.OP]);
    if(current_instruction.OP == ISA_COUNT)
    {
        uint32_t log_reg_data = 0;
        current_instruction.dr = 0;
        current_instruction.OP = ECALL;
    }

//    printf("PC: 0x%08X, Instruction: 0x%08X, OP: %d ===> \n", PC, imem[(PC -IM_OFFSET) >> 2], current_instruction.dr);
    fprintf( fp, "%08X | %08X |  %-6s | %-7d | %08X | %08X | %08X   %d\n", 
        PC,
        imem[(PC - IM_OFFSET) >> 2],
        ISA_names[current_instruction.OP],
        current_instruction.dr,     
        log_reg_data,               //registerFile[current_instruction.dr],  
        log_addr_dm,                //address_dm,
        log_dmem_data,               //dmem[address_dm & DMEM_MASK]
        cycles
    );

}

uint8_t is_reg_write(ISA op)
{
    return (op == ADD || op == SUB || op == SLL || op == SLT || op == SLTU || op == XOR || op == SRL || op == SRA || op == OR || op == AND ||
            op == ADDI || op == SLTI || op == SLTIU || op == XORI || op == ORI || op == ANDI || op == SLLI || op == SRLI || op == SRAI ||
            op == LB || op == LH || op == LW || op == LBU || op == LHU ||
            op == JAL || op == JALR ||
            op == LUI || op == AUIPC);

}

uint8_t is_mem_access(ISA op)
{
    return ( op == SB || op == SH || op == SW );
}


void print_instr_memory() {
    printf("Instruction Memory:\n");
    for(int i = 0; i < IMEM_SIZE; i++) {
        printf("0x%08X: 0x%08X\n", IM_OFFSET + (i * 4), imem[i]);
    }
}

void print_data_memory(int n) {
    printf("Data memory:\n");
    for(int i = 0; i < n; i++)
    {
        printf("0x%08X: 0x%02X\n", DM_OFFSET + (i), dmem[i]);
    }
}